baseURL = "https://jsantacruzpy.github.io/blog"
languageCode = "es"
theme = "hugo-coder"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[params]
  author = "Jose Santacruz"
  description = "Consultor Tecnologico"
  info = "VMware VCP | Cisco CCNP ENCORE | AWS Cloud Architect | Microsoft MTA  Consultor en Tecnologías de la Información"
  avatarURL = "images/profile.jpg"
  colorScheme = "auto"
  hideColorSchemeToggle = false
  since = 2025

[menu]
  [[menu.main]]
  name = "Inicio"
  url  = "/"
  weight = 1

    [[menu.main]]
  name = "Posts"
  url  = "/posts/"
  weight = 2

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/jsantacruzpy"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/jose-santacruz-14202b170/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://jsantacruzpy.github.io/blog/"
rel = "alternate"
type = "application/rss+xml"
